export const resData = [
  {
    id: 1,
    name: "The Spice House",
    cuisine: ["Indian", "Thai"],
    rating: 4.5,
    reviews: 120,
    priceRange: "$$",
    isOpen: true,
    deliveryTime: "30-40 mins",
    imageUrl: "https://example.com/images/spice-house.jpg",
    location: {
      address: "123 Curry St",
      city: "Mumbai",
      zipCode: "400001",
    },
  },
  {
    id: 2,
    name: "Burger Bliss",
    cuisine: ["American", "Fast Food"],
    rating: 4.2,
    reviews: 95,
    priceRange: "$",
    isOpen: false,
    deliveryTime: "20-25 mins",
    imageUrl: "https://example.com/images/burger-bliss.jpg",
    location: {
      address: "45 Grill Avenue",
      city: "Bangalore",
      zipCode: "560001",
    },
  },
  {
    id: 3,
    name: "Sushi Samba",
    cuisine: ["Japanese", "Seafood"],
    rating: 4.8,
    reviews: 210,
    priceRange: "$$$",
    isOpen: true,
    deliveryTime: "40-50 mins",
    imageUrl: "https://example.com/images/sushi-samba.jpg",
    location: {
      address: "789 Ocean Drive",
      city: "Chennai",
      zipCode: "600002",
    },
  },
  {
    id: 4,
    name: "Pizza Planet",
    cuisine: ["Italian", "Pizza"],
    rating: 4.1,
    reviews: 180,
    priceRange: "$$",
    isOpen: true,
    deliveryTime: "25-35 mins",
    imageUrl: "https://example.com/images/pizza-planet.jpg",
    location: {
      address: "321 Mozzarella Blvd",
      city: "Delhi",
      zipCode: "110001",
    },
  },
  {
    id: 5,
    name: "Green Garden",
    cuisine: ["Vegan", "Salads"],
    rating: 4.6,
    reviews: 140,
    priceRange: "$$",
    isOpen: false,
    deliveryTime: "20-30 mins",
    imageUrl: "https://example.com/images/green-garden.jpg",
    location: {
      address: "18 Herb Lane",
      city: "Pune",
      zipCode: "411001",
    },
  },
  {
    id: 6,
    name: "Taco Fiesta",
    cuisine: ["Mexican"],
    rating: 4.3,
    reviews: 102,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "15-20 mins",
    imageUrl: "https://example.com/images/taco-fiesta.jpg",
    location: {
      address: "500 Fiesta St",
      city: "Ahmedabad",
      zipCode: "380001",
    },
  },
  {
    id: 7,
    name: "Dragon Wok",
    cuisine: ["Chinese", "Asian"],
    rating: 4.4,
    reviews: 160,
    priceRange: "$$",
    isOpen: true,
    deliveryTime: "35-45 mins",
    imageUrl: "https://example.com/images/dragon-wok.jpg",
    location: {
      address: "66 Panda Road",
      city: "Kolkata",
      zipCode: "700001",
    },
  },
  {
    id: 8,
    name: "Biryani Bistro",
    cuisine: ["Indian", "Hyderabadi"],
    rating: 4.7,
    reviews: 220,
    priceRange: "$$",
    isOpen: false,
    deliveryTime: "30-35 mins",
    imageUrl: "https://example.com/images/biryani-bistro.jpg",
    location: {
      address: "404 Nawab Street",
      city: "Hyderabad",
      zipCode: "500001",
    },
  },
  {
    id: 9,
    name: "Continental Delight",
    cuisine: ["European", "Continental"],
    rating: 4.0,
    reviews: 88,
    priceRange: "$$$",
    isOpen: true,
    deliveryTime: "45-55 mins",
    imageUrl: "https://example.com/images/continental-delight.jpg",
    location: {
      address: "28 Gourmet Ave",
      city: "Jaipur",
      zipCode: "302001",
    },
  },
  {
    id: 10,
    name: "Street Treats",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 11,
    name: "Street Treats",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 12,
    name: "Cofee Corner",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 13,
    name: "Mama's Kitchen",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 14,
    name: "t",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 15,
    name: "ram ki chai",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 87,
    name: "happy Meals",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 98,
    name: "foodies Hub",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 131,
    name: "roadside Dhaba",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 17,
    name: "quality Eats",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 18,
    name: "best Bites",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 19,
    name: "lucky's Kitchen",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 21,
    name: "amazing Eats",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 23,
    name: "local Bites",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
  {
    id: 24,
    name: "mom's Kitchen",
    cuisine: ["Street Food", "Snacks"],
    rating: 4.9,
    reviews: 300,
    priceRange: "$",
    isOpen: true,
    deliveryTime: "10-15 mins",
    imageUrl: "https://example.com/images/street-treats.jpg",
    location: {
      address: "12 Chaat Circle",
      city: "Lucknow",
      zipCode: "226001",
    },
  },
];
